app:
  updatable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_ticket_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true